
### POST Register
POST  http://localhost:4040/api/auth/register
Content-Type: application/json

{
    "username":"trungee",
    "email":"truggnpoly@gmail.com",
    "password":"thinh",
    "avata":"trung.jpg"
}


### POST Login
POST  http://localhost:4040/api/auth/login
Content-Type: application/json

{
    "email":"admin@gmail.com",
    "password":"admin"
}

### POST Create posts
POST http://localhost:4040/api/posts/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDczMWJmMjJiODVjNDJmNWM5NzdiMmIiLCJpYXQiOjE2MTgzMjc4NjR9.aGUpwxyZn-A36As0CCNuyuN6WuwwY0JjzyKenYdqcI8


{
    "title":"JavaScript_admin1",
    "description":"làm quen với Javascript",
    "url":"js.org.com",
    "like":"10",
    "view":"10",
    "image":"123.jpg",
    "speciesId":["607070276b0c8702ac8bbfdf"]
   
}

### GET POSTS
GET http://localhost:4040/api/posts


### UPDATE POSTS
PUT http://localhost:4040/api/posts/60747d915dd94a3fe40f3ce5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDc0N2Q2ODVkZDk0YTNmZTQwZjNjZTQiLCJpYXQiOjE2MTgyNDcwMjl9.Jk5-vmCFL9wlORjbLZpoASKnf79RbaN66xwqBSkNj4o

{
    "title":"java1111112",
    "description":"java111",
    "url":"java.org.com",
    "image":"java.jpg",
    "speciesId": "60702a33a30b0f265c92b4f2"
    
    
}


### DELETE POSTS
PATCH   http://localhost:4040/api/posts/607502fd0b52743a241e9774
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDc1MDJlMjBiNTI3NDNhMjQxZTk3NzMiLCJpYXQiOjE2MTgyODExOTh9.hPeLf4srX-h_esx4NEVP_Qe-EJFxSN3fwZ91Lngo3U8


### POST SPECIESPOST
POST http://localhost:4040/api/posts/postspecies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDczMWU4MmY4ZDEyMTM0MDhkMjdkZjgiLCJpYXQiOjE2MTgxNTcyMDF9.rvs5VPJTDQ351jxHUafKKSpKNJrCH2C7avBC1zNU86M

{
    "species":"JavaSctript",
    "description":"javajs"
}

### PATCH Comment 
PATCH http://localhost:4040/api/posts/60727a7f3c674c1ae86169df
Content-Type: : application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDZmMmRhZWU2YWE2OTA3MDQyYWJlNWIiLCJpYXQiOjE2MTgxMTQ5MzR9.KFB8Pv5k_kNbjlG9be3j0Mk-K8Y7zYTExG8rnYS7lmo

{
    "comments":[
        {
            "content":"hello ban trung",
            "IdUserComment":"606f2daee6aa6907042abe5b"
        }
    ]
}


### GET DATA BY USER 
GET http://localhost:4040/api/posts/posts-by-user/607502e20b52743a241e9773
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDc1MDJlMjBiNTI3NDNhMjQxZTk3NzMiLCJpYXQiOjE2MTgyODExOTh9.hPeLf4srX-h_esx4NEVP_Qe-EJFxSN3fwZ91Lngo3U8


### @ PATCH LOCK ACOUNT
PATCH http://localhost:4040/api/admin/lock-acount/6073f0e6e9eaef2960bc5b04
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDczMWJmMjJiODVjNDJmNWM5NzdiMmIiLCJpYXQiOjE2MTgyMTEwNjl9.FXRRouqmRaDLEpgHtNCmTmTNP0Z_0RwhyVwUydgKlzs


### @ PATCH OPEN LOCK ACOUNT
PATCH http://localhost:4040/api/admin/open-acount/6073f0e6e9eaef2960bc5b04
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDczMWJmMjJiODVjNDJmNWM5NzdiMmIiLCJpYXQiOjE2MTgyMTEwNjl9.FXRRouqmRaDLEpgHtNCmTmTNP0Z_0RwhyVwUydgKlzs

### @ PATCH EXECUTED POSTS
PATCH http://localhost:4040/api/admin/executed-post/60746552c383ae43c4e96d12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDczMWJmMjJiODVjNDJmNWM5NzdiMmIiLCJpYXQiOjE2MTgyNDQwMjR9.tFGmYpVFmALiiEmiV6hUhaIMfnKiNGWwHv4Q_-a5gxM

### @ PATCH BLOCK POSTS
PATCH  http://localhost:4040/api/admin/block-post/60746552c383ae43c4e96d12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDczMWJmMjJiODVjNDJmNWM5NzdiMmIiLCJpYXQiOjE2MTgyNDQwMjR9.tFGmYpVFmALiiEmiV6hUhaIMfnKiNGWwHv4Q_-a5gxM

### @ DESTROY POST {role: 'admin'}
DELETE http://localhost:4040/api/admin/destroy-post/60741769e680712df0e107e1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDc0MTdhZGU2ODA3MTJkZjBlMTA3ZTIiLCJpYXQiOjE2MTgyNDQ3MzF9.1rSNhiYXbYd5K9xWkyz763-eR-gNcqSETIC4gc8nl7E

### GET DATA POST BY SPECIES
GET http://localhost:4040/api/posts/species/607070276b0c8702ac8bbfdf

### PATCH UPDATE PASSWORD USER
PATCH http://localhost:4040/api/user/update-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDc1MDJlMjBiNTI3NDNhMjQxZTk3NzMiLCJpYXQiOjE2MTgyODc0Mjh9.ubmsc6lQLwn7EJs10eYtW8nBN0kIqTp2_uhGuX7weKo

{
    "oldPassword":"thinddf",
    "newPassword":"thinddfh"
}

### PUT UPDATE ACOUNT 
PUT http://localhost:4040/api/user/update-acount
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDc1MDJlMjBiNTI3NDNhMjQxZTk3NzMiLCJpYXQiOjE2MTgyOTAyNDh9.r8wL5oM91TtDzE9jvNv_02lyVdObibylrGMeqigPi18

{
    "username":"trung44444",
    "avata":"trung.jpg"
}

### Confirm Account by Admin
PUT  http://localhost:4040/api/admin/confirm-role/607effe668a50625043b07e2
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDczMWJmMjJiODVjNDJmNWM5NzdiMmIiLCJpYXQiOjE2MTg5Mzc1NzR9.AsdYJLP7bKPjMD0MACKPwVh4Wmlv377jJWxPLogwCgk