
### POST Register
POST  http://localhost:4040/api/auth/register
Content-Type: application/json

{
    "username":"hoa",
    "email":"hoa@gmail.com",
    "password":"hoa"
}


### POST Login
POST  http://localhost:4040/api/auth/login
Content-Type: application/json

{
    "email":"hoa@gmail.com",
    "password":"hoa"
}

### POST Create posts
POST http://localhost:4040/api/posts/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDc0N2Q2ODVkZDk0YTNmZTQwZjNjZTQiLCJpYXQiOjE2MTgyNDcwMjl9.Jk5-vmCFL9wlORjbLZpoASKnf79RbaN66xwqBSkNj4o


{
    "title":"JavaScript_hoa",
    "description":"làm quen với Javascript",
    "url":"js.org.com",
    "image":"123.jpg",
    "speciesId":["60702a33a30b0f265c92b4f2"]
   
}

### GET POSTS
GET http://localhost:4040/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDZmMmRhZWU2YWE2OTA3MDQyYWJlNWIiLCJpYXQiOjE2MTc4OTg5MzB9.tl2D9U5wRupRGJP6HJb4Glk8R0jb9pHzwuYrJt-LO30


### UPDATE POSTS
PUT http://localhost:4040/api/posts/60747d915dd94a3fe40f3ce5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDc0N2Q2ODVkZDk0YTNmZTQwZjNjZTQiLCJpYXQiOjE2MTgyNDcwMjl9.Jk5-vmCFL9wlORjbLZpoASKnf79RbaN66xwqBSkNj4o

{
    "title":"java111",
    "description":"java111",
    "url":"java.org.com",
    "image":"java.jpg",
    "speciesId": "60702a33a30b0f265c92b4f2"
    
    
}


### DELETE POSTS
DELETE  http://localhost:4040/api/posts/606f2ddde6aa6907042abe5c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDZmMmRhZWU2YWE2OTA3MDQyYWJlNWIiLCJpYXQiOjE2MTc4OTg5MzB9.tl2D9U5wRupRGJP6HJb4Glk8R0jb9pHzwuYrJt-LO30


### POST SPECIESPOST
POST http://localhost:4040/api/posts/postspecies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDczMWU4MmY4ZDEyMTM0MDhkMjdkZjgiLCJpYXQiOjE2MTgxNTcyMDF9.rvs5VPJTDQ351jxHUafKKSpKNJrCH2C7avBC1zNU86M

{
    "species":"JavaSctript",
    "description":"javajs"
}

### PATCH Comment 
PATCH http://localhost:4040/api/posts/60727a7f3c674c1ae86169df
Content-Type: : application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDZmMmRhZWU2YWE2OTA3MDQyYWJlNWIiLCJpYXQiOjE2MTgxMTQ5MzR9.KFB8Pv5k_kNbjlG9be3j0Mk-K8Y7zYTExG8rnYS7lmo

{
    "comments":[
        {
            "content":"hello ban trung",
            "IdUserComment":"606f2daee6aa6907042abe5b"
        }
    ]
}


### GET DATA BY USER 
GET http://localhost:4040/api/posts/posts-by-user/607479c15dd94a3fe40f3ce2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDc0NzljMTVkZDk0YTNmZTQwZjNjZTIiLCJpYXQiOjE2MTgyNDYwOTR9.OauvKmOPI8HY2WEXoAcHAhUHF2WWjDWPYDV5ufWLR5M


### @ PATCH LOCK ACOUNT
PATCH http://localhost:4040/api/admin/lock-acount/6073f0e6e9eaef2960bc5b04
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDczMWJmMjJiODVjNDJmNWM5NzdiMmIiLCJpYXQiOjE2MTgyMTEwNjl9.FXRRouqmRaDLEpgHtNCmTmTNP0Z_0RwhyVwUydgKlzs


### @ PATCH OPEN LOCK ACOUNT
PATCH http://localhost:4040/api/admin/open-acount/6073f0e6e9eaef2960bc5b04
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDczMWJmMjJiODVjNDJmNWM5NzdiMmIiLCJpYXQiOjE2MTgyMTEwNjl9.FXRRouqmRaDLEpgHtNCmTmTNP0Z_0RwhyVwUydgKlzs

### @ PATCH EXECUTED POSTS
PATCH http://localhost:4040/api/admin/executed-post/60746552c383ae43c4e96d12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDczMWJmMjJiODVjNDJmNWM5NzdiMmIiLCJpYXQiOjE2MTgyNDQwMjR9.tFGmYpVFmALiiEmiV6hUhaIMfnKiNGWwHv4Q_-a5gxM

### @ PATCH BLOCK POSTS
PATCH  http://localhost:4040/api/admin/block-post/60746552c383ae43c4e96d12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDczMWJmMjJiODVjNDJmNWM5NzdiMmIiLCJpYXQiOjE2MTgyNDQwMjR9.tFGmYpVFmALiiEmiV6hUhaIMfnKiNGWwHv4Q_-a5gxM

### @ DESTROY POST {role: 'admin'}
DELETE http://localhost:4040/api/admin/destroy-post/60741769e680712df0e107e1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDc0MTdhZGU2ODA3MTJkZjBlMTA3ZTIiLCJpYXQiOjE2MTgyNDQ3MzF9.1rSNhiYXbYd5K9xWkyz763-eR-gNcqSETIC4gc8nl7E

